const EMAIL_MESSAGE_PROCESSOR = 'Email Message Processor';
const PUSH_NOTIFICATION_PROCESSOR = 'Push Notification Processor';

exports.EMAIL_MESSAGE_PROCESSOR = EMAIL_MESSAGE_PROCESSOR;
exports.PUSH_NOTIFICATION_PROCESSOR = PUSH_NOTIFICATION_PROCESSOR;
exports.registeredJobs = [EMAIL_MESSAGE_PROCESSOR, PUSH_NOTIFICATION_PROCESSOR];
